// Mocks generated by Mockito 5.4.6 from annotations
// in flower_app/test/features/commerce/presentation/home/view_model/home_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flower_app/core/base/base_response.dart' as _i5;
import 'package:flower_app/features/commerce/domain/entities/home_layout_entity.dart'
    as _i6;
import 'package:flower_app/features/commerce/domain/repo/commerce_repo.dart'
    as _i2;
import 'package:flower_app/features/commerce/domain/use_cases/home_use_case.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCommerceRepo_0 extends _i1.SmartFake implements _i2.CommerceRepo {
  _FakeCommerceRepo_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [HomeUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeUseCase extends _i1.Mock implements _i3.HomeUseCase {
  MockHomeUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CommerceRepo get repo =>
      (super.noSuchMethod(
            Invocation.getter(#repo),
            returnValue: _FakeCommerceRepo_0(this, Invocation.getter(#repo)),
          )
          as _i2.CommerceRepo);

  @override
  _i4.Future<_i5.BaseResponse<_i6.HomeLayoutEntity>> call({String? storeId}) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#storeId: storeId}),
            returnValue:
                _i4.Future<_i5.BaseResponse<_i6.HomeLayoutEntity>>.value(
                  _i7.dummyValue<_i5.BaseResponse<_i6.HomeLayoutEntity>>(
                    this,
                    Invocation.method(#call, [], {#storeId: storeId}),
                  ),
                ),
          )
          as _i4.Future<_i5.BaseResponse<_i6.HomeLayoutEntity>>);
}
