// Mocks generated by Mockito 5.4.6 from annotations
// in flower_app/test/features/forget_password/presentation/view_model/forget_password_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flower_app/core/base/base_response.dart' as _i5;
import 'package:flower_app/features/forget_password/domain/entities/forget_password_entity.dart'
    as _i6;
import 'package:flower_app/features/forget_password/domain/entities/forget_password_params.dart'
    as _i7;
import 'package:flower_app/features/forget_password/domain/entities/reset_password_entity.dart'
    as _i13;
import 'package:flower_app/features/forget_password/domain/entities/reset_password_params.dart'
    as _i14;
import 'package:flower_app/features/forget_password/domain/entities/verify_otp_entity.dart'
    as _i10;
import 'package:flower_app/features/forget_password/domain/entities/verify_otp_params.dart'
    as _i11;
import 'package:flower_app/features/forget_password/domain/repos/forget_password_repo.dart'
    as _i2;
import 'package:flower_app/features/forget_password/domain/use_cases/forget_password_use_case.dart'
    as _i3;
import 'package:flower_app/features/forget_password/domain/use_cases/reset_password_use_case.dart'
    as _i12;
import 'package:flower_app/features/forget_password/domain/use_cases/verify_otp_use_case.dart'
    as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeForgetPasswordRepo_0 extends _i1.SmartFake
    implements _i2.ForgetPasswordRepo {
  _FakeForgetPasswordRepo_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ForgetPasswordUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockForgetPasswordUseCase extends _i1.Mock
    implements _i3.ForgetPasswordUseCase {
  MockForgetPasswordUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ForgetPasswordRepo get forgetPasswordRepo =>
      (super.noSuchMethod(
            Invocation.getter(#forgetPasswordRepo),
            returnValue: _FakeForgetPasswordRepo_0(
              this,
              Invocation.getter(#forgetPasswordRepo),
            ),
          )
          as _i2.ForgetPasswordRepo);

  @override
  _i4.Future<_i5.BaseResponse<_i6.ForgetPasswordEntity>> call({
    required _i7.ForgetPasswordParams? forgetPasswordParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #forgetPasswordParams: forgetPasswordParams,
            }),
            returnValue:
                _i4.Future<_i5.BaseResponse<_i6.ForgetPasswordEntity>>.value(
                  _i8.dummyValue<_i5.BaseResponse<_i6.ForgetPasswordEntity>>(
                    this,
                    Invocation.method(#call, [], {
                      #forgetPasswordParams: forgetPasswordParams,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i5.BaseResponse<_i6.ForgetPasswordEntity>>);
}

/// A class which mocks [VerifyOtpUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockVerifyOtpUseCase extends _i1.Mock implements _i9.VerifyOtpUseCase {
  MockVerifyOtpUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ForgetPasswordRepo get forgetPasswordRepo =>
      (super.noSuchMethod(
            Invocation.getter(#forgetPasswordRepo),
            returnValue: _FakeForgetPasswordRepo_0(
              this,
              Invocation.getter(#forgetPasswordRepo),
            ),
          )
          as _i2.ForgetPasswordRepo);

  @override
  _i4.Future<_i5.BaseResponse<_i10.VerifyOtpEntity>> call({
    required _i11.VerifyOtpParams? verifyOtpParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#verifyOtpParams: verifyOtpParams}),
            returnValue:
                _i4.Future<_i5.BaseResponse<_i10.VerifyOtpEntity>>.value(
                  _i8.dummyValue<_i5.BaseResponse<_i10.VerifyOtpEntity>>(
                    this,
                    Invocation.method(#call, [], {
                      #verifyOtpParams: verifyOtpParams,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i5.BaseResponse<_i10.VerifyOtpEntity>>);
}

/// A class which mocks [ResetPasswordUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockResetPasswordUseCase extends _i1.Mock
    implements _i12.ResetPasswordUseCase {
  MockResetPasswordUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ForgetPasswordRepo get forgetPasswordRepo =>
      (super.noSuchMethod(
            Invocation.getter(#forgetPasswordRepo),
            returnValue: _FakeForgetPasswordRepo_0(
              this,
              Invocation.getter(#forgetPasswordRepo),
            ),
          )
          as _i2.ForgetPasswordRepo);

  @override
  _i4.Future<_i5.BaseResponse<_i13.ResetPasswordEntity>> call({
    required _i14.ResetPasswordParams? resetPasswordParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #resetPasswordParams: resetPasswordParams,
            }),
            returnValue:
                _i4.Future<_i5.BaseResponse<_i13.ResetPasswordEntity>>.value(
                  _i8.dummyValue<_i5.BaseResponse<_i13.ResetPasswordEntity>>(
                    this,
                    Invocation.method(#call, [], {
                      #resetPasswordParams: resetPasswordParams,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i5.BaseResponse<_i13.ResetPasswordEntity>>);
}
