// Mocks generated by Mockito 5.4.6 from annotations
// in flower_app/test/features/forget_password/api/data_source/forget_password_remote_data_source_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flower_app/core/base/base_response.dart' as _i9;
import 'package:flower_app/core/network/safe_call.dart' as _i8;
import 'package:flower_app/features/forget_password/api/client/forget_password_api_client.dart'
    as _i4;
import 'package:flower_app/features/forget_password/data/models/forget_password_request_model.dart'
    as _i6;
import 'package:flower_app/features/forget_password/data/models/forget_password_response_model.dart'
    as _i2;
import 'package:flower_app/features/forget_password/data/models/verify_otp_request_model.dart'
    as _i7;
import 'package:flower_app/features/forget_password/data/models/verify_otp_response_model.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeForgetPasswordResponseModel_0 extends _i1.SmartFake
    implements _i2.ForgetPasswordResponseModel {
  _FakeForgetPasswordResponseModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeVerifyOtpResponseModel_1 extends _i1.SmartFake
    implements _i3.VerifyOtpResponseModel {
  _FakeVerifyOtpResponseModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ForgetPasswordApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockForgetPasswordApiClient extends _i1.Mock
    implements _i4.ForgetPasswordApiClient {
  MockForgetPasswordApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.ForgetPasswordResponseModel> forgotPassword(
    _i6.ForgetPasswordRequestModel? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#forgotPassword, [request]),
            returnValue: _i5.Future<_i2.ForgetPasswordResponseModel>.value(
              _FakeForgetPasswordResponseModel_0(
                this,
                Invocation.method(#forgotPassword, [request]),
              ),
            ),
          )
          as _i5.Future<_i2.ForgetPasswordResponseModel>);

  @override
  _i5.Future<_i3.VerifyOtpResponseModel> verifyOtp(
    _i7.VerifyOtpRequestModel? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verifyOtp, [request]),
            returnValue: _i5.Future<_i3.VerifyOtpResponseModel>.value(
              _FakeVerifyOtpResponseModel_1(
                this,
                Invocation.method(#verifyOtp, [request]),
              ),
            ),
          )
          as _i5.Future<_i3.VerifyOtpResponseModel>);
}

/// A class which mocks [SafeCall].
///
/// See the documentation for Mockito's code generation for more information.
class MockSafeCall extends _i1.Mock implements _i8.SafeCall {
  MockSafeCall() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i9.BaseResponse<T>> safeApiCall<T>(
    _i5.Future<T> Function()? apiCall,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#safeApiCall, [apiCall]),
            returnValue: _i5.Future<_i9.BaseResponse<T>>.value(
              _i10.dummyValue<_i9.BaseResponse<T>>(
                this,
                Invocation.method(#safeApiCall, [apiCall]),
              ),
            ),
          )
          as _i5.Future<_i9.BaseResponse<T>>);
}
