// Flower-themed dummy product data for development and testing

import 'package:flower_app/features/commerce/domain/models/product_request.dart';

const List<Product> dummyProducts = [
  Product(
    imageUrl: 'https://picsum.photos/seed/rose/600/400',
    name: 'Red Rose Bouquet',
    price: '\$25.00',
    oldPrice: '\$30.00',
    discount: '17%',
    isOutOfStock: false,
  ),
  Product(
    imageUrl: 'https://picsum.photos/seed/tulip/600/400',
    name: 'Spring Tulips',
    price: '\$18.00',
    oldPrice: null,
    discount: null,
    isOutOfStock: false,
  ),
  Product(
    imageUrl: 'https://picsum.photos/seed/lily/600/400',
    name: 'White Lily Bunch',
    price: '\$22.50',
    oldPrice: '\$27.00',
    discount: '16%',
    isOutOfStock: false,
  ),
  Product(
    imageUrl: 'https://picsum.photos/seed/orchid/600/400',
    name: 'Elegant Orchids',
    price: '\$40.00',
    oldPrice: null,
    discount: null,
    isOutOfStock: true,
  ),
  Product(
    imageUrl: 'https://picsum.photos/seed/sunflower/600/400',
    name: 'Sunflower Surprise',
    price: '\$15.00',
    oldPrice: '\$20.00',
    discount: '25%',
    isOutOfStock: false,
  ),
  Product(
    imageUrl: 'https://picsum.photos/seed/mixed/600/400',
    name: 'Mixed Seasonal Bouquet',
    price: '\$30.00',
    oldPrice: null,
    discount: null,
    isOutOfStock: false,
  ),
  Product(
    imageUrl: 'https://picsum.photos/seed/peony/600/400',
    name: 'Pink Peonies',
    price: '\$35.00',
    oldPrice: '\$45.00',
    discount: '22%',
    isOutOfStock: false,
  ),
  Product(
    imageUrl: 'https://picsum.photos/seed/daisy/600/400',
    name: 'Sunny Daisies',
    price: '\$12.00',
    oldPrice: null,
    discount: null,
    isOutOfStock: false,
  ),
  Product(
    imageUrl: 'https://picsum.photos/seed/lavender/600/400',
    name: 'Lavender Wrap',
    price: '\$20.00',
    oldPrice: '\$24.00',
    discount: '17%',
    isOutOfStock: false,
  ),
  Product(
    imageUrl: 'https://picsum.photos/seed/gardenia/600/400',
    name: 'Gardenia Classic',
    price: '\$28.00',
    oldPrice: null,
    discount: null,
    isOutOfStock: true,
  ),
];
