// Mocks generated by Mockito 5.4.6 from annotations
// in flower_app/test/features/forget_password/data/repos/forget_password_repo_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flower_app/core/base/base_response.dart' as _i4;
import 'package:flower_app/features/forget_password/data/data_sources/remote/forget_password_remote_data_source.dart'
    as _i2;
import 'package:flower_app/features/forget_password/data/models/forget_password_request_model.dart'
    as _i6;
import 'package:flower_app/features/forget_password/data/models/forget_password_response_model.dart'
    as _i5;
import 'package:flower_app/features/forget_password/data/models/reset_password_request_model.dart'
    as _i11;
import 'package:flower_app/features/forget_password/data/models/reset_password_response_model.dart'
    as _i10;
import 'package:flower_app/features/forget_password/data/models/verify_otp_request_model.dart'
    as _i9;
import 'package:flower_app/features/forget_password/data/models/verify_otp_response_model.dart'
    as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ForgetPasswordRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockForgetPasswordRemoteDataSource extends _i1.Mock
    implements _i2.ForgetPasswordRemoteDataSource {
  MockForgetPasswordRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.BaseResponse<_i5.ForgetPasswordResponseModel>> forgetPassword({
    required _i6.ForgetPasswordRequestModel? requestModel,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#forgetPassword, [], {
              #requestModel: requestModel,
            }),
            returnValue:
                _i3.Future<
                  _i4.BaseResponse<_i5.ForgetPasswordResponseModel>
                >.value(
                  _i7.dummyValue<
                    _i4.BaseResponse<_i5.ForgetPasswordResponseModel>
                  >(
                    this,
                    Invocation.method(#forgetPassword, [], {
                      #requestModel: requestModel,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.BaseResponse<_i5.ForgetPasswordResponseModel>>);

  @override
  _i3.Future<_i4.BaseResponse<_i8.VerifyOtpResponseModel>> verifyOtp({
    required _i9.VerifyOtpRequestModel? requestModel,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifyOtp, [], {#requestModel: requestModel}),
            returnValue:
                _i3.Future<_i4.BaseResponse<_i8.VerifyOtpResponseModel>>.value(
                  _i7.dummyValue<_i4.BaseResponse<_i8.VerifyOtpResponseModel>>(
                    this,
                    Invocation.method(#verifyOtp, [], {
                      #requestModel: requestModel,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.BaseResponse<_i8.VerifyOtpResponseModel>>);

  @override
  _i3.Future<_i4.BaseResponse<_i10.ResetPasswordResponseModel>> resetPassword({
    required _i11.ResetPasswordRequestModel? requestModel,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [], {
              #requestModel: requestModel,
            }),
            returnValue:
                _i3.Future<
                  _i4.BaseResponse<_i10.ResetPasswordResponseModel>
                >.value(
                  _i7.dummyValue<
                    _i4.BaseResponse<_i10.ResetPasswordResponseModel>
                  >(
                    this,
                    Invocation.method(#resetPassword, [], {
                      #requestModel: requestModel,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.BaseResponse<_i10.ResetPasswordResponseModel>>);
}
