// Mocks generated by Mockito 5.4.6 from annotations
// in flower_app/test/features/forget_password/data/repos/verify_otp_repo_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flower_app/core/base/base_response.dart' as _i6;
import 'package:flower_app/core/network/safe_call.dart' as _i3;
import 'package:flower_app/features/forget_password/api/client/forget_password_api_client.dart'
    as _i2;
import 'package:flower_app/features/forget_password/api/data_source/forget_password_remote_data_source_impl.dart'
    as _i4;
import 'package:flower_app/features/forget_password/data/models/forget_password_request_model.dart'
    as _i8;
import 'package:flower_app/features/forget_password/data/models/forget_password_response_model.dart'
    as _i7;
import 'package:flower_app/features/forget_password/data/models/verify_otp_request_model.dart'
    as _i11;
import 'package:flower_app/features/forget_password/data/models/verify_otp_response_model.dart'
    as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeForgetPasswordApiClient_0 extends _i1.SmartFake
    implements _i2.ForgetPasswordApiClient {
  _FakeForgetPasswordApiClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSafeCall_1 extends _i1.SmartFake implements _i3.SafeCall {
  _FakeSafeCall_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ForgetPasswordRemoteDataSourceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockForgetPasswordRemoteDataSourceImpl extends _i1.Mock
    implements _i4.ForgetPasswordRemoteDataSourceImpl {
  MockForgetPasswordRemoteDataSourceImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ForgetPasswordApiClient get forgetPasswordApiClient =>
      (super.noSuchMethod(
            Invocation.getter(#forgetPasswordApiClient),
            returnValue: _FakeForgetPasswordApiClient_0(
              this,
              Invocation.getter(#forgetPasswordApiClient),
            ),
          )
          as _i2.ForgetPasswordApiClient);

  @override
  _i3.SafeCall get safeCall =>
      (super.noSuchMethod(
            Invocation.getter(#safeCall),
            returnValue: _FakeSafeCall_1(this, Invocation.getter(#safeCall)),
          )
          as _i3.SafeCall);

  @override
  _i5.Future<_i6.BaseResponse<_i7.ForgetPasswordResponseModel>> forgetPassword({
    required _i8.ForgetPasswordRequestModel? requestModel,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#forgetPassword, [], {
              #requestModel: requestModel,
            }),
            returnValue:
                _i5.Future<
                  _i6.BaseResponse<_i7.ForgetPasswordResponseModel>
                >.value(
                  _i9.dummyValue<
                    _i6.BaseResponse<_i7.ForgetPasswordResponseModel>
                  >(
                    this,
                    Invocation.method(#forgetPassword, [], {
                      #requestModel: requestModel,
                    }),
                  ),
                ),
          )
          as _i5.Future<_i6.BaseResponse<_i7.ForgetPasswordResponseModel>>);

  @override
  _i5.Future<_i6.BaseResponse<_i10.VerifyOtpResponseModel>> verifyOtp({
    required _i11.VerifyOtpRequestModel? requestModel,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifyOtp, [], {#requestModel: requestModel}),
            returnValue:
                _i5.Future<_i6.BaseResponse<_i10.VerifyOtpResponseModel>>.value(
                  _i9.dummyValue<_i6.BaseResponse<_i10.VerifyOtpResponseModel>>(
                    this,
                    Invocation.method(#verifyOtp, [], {
                      #requestModel: requestModel,
                    }),
                  ),
                ),
          )
          as _i5.Future<_i6.BaseResponse<_i10.VerifyOtpResponseModel>>);
}
