// Mocks generated by Mockito 5.4.6 from annotations
// in flower_app/test/features/commerce/domain/use_cases/home_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flower_app/core/base/base_response.dart' as _i4;
import 'package:flower_app/features/commerce/data/models/occasion_model.dart'
    as _i8;
import 'package:flower_app/features/commerce/domain/entities/category_entity.dart'
    as _i10;
import 'package:flower_app/features/commerce/domain/entities/home_layout_entity.dart'
    as _i5;
import 'package:flower_app/features/commerce/domain/entities/product_details_entity.dart'
    as _i9;
import 'package:flower_app/features/commerce/domain/entities/product_entity.dart'
    as _i7;
import 'package:flower_app/features/commerce/domain/repo/commerce_repo.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [CommerceRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockCommerceRepo extends _i1.Mock implements _i2.CommerceRepo {
  MockCommerceRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.BaseResponse<_i5.HomeLayoutEntity>> getHomeLayout({
    String? storeId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getHomeLayout, [], {#storeId: storeId}),
            returnValue:
                _i3.Future<_i4.BaseResponse<_i5.HomeLayoutEntity>>.value(
                  _i6.dummyValue<_i4.BaseResponse<_i5.HomeLayoutEntity>>(
                    this,
                    Invocation.method(#getHomeLayout, [], {#storeId: storeId}),
                  ),
                ),
          )
          as _i3.Future<_i4.BaseResponse<_i5.HomeLayoutEntity>>);

  @override
  _i3.Future<_i4.BaseResponse<List<_i7.ProductEntity>>> getProducts({
    String? occasionId,
    String? categoryId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getProducts, [], {
              #occasionId: occasionId,
              #categoryId: categoryId,
            }),
            returnValue:
                _i3.Future<_i4.BaseResponse<List<_i7.ProductEntity>>>.value(
                  _i6.dummyValue<_i4.BaseResponse<List<_i7.ProductEntity>>>(
                    this,
                    Invocation.method(#getProducts, [], {
                      #occasionId: occasionId,
                      #categoryId: categoryId,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.BaseResponse<List<_i7.ProductEntity>>>);

  @override
  _i3.Future<_i4.BaseResponse<List<_i8.OccasionModel>>> getAllOccasions() =>
      (super.noSuchMethod(
            Invocation.method(#getAllOccasions, []),
            returnValue:
                _i3.Future<_i4.BaseResponse<List<_i8.OccasionModel>>>.value(
                  _i6.dummyValue<_i4.BaseResponse<List<_i8.OccasionModel>>>(
                    this,
                    Invocation.method(#getAllOccasions, []),
                  ),
                ),
          )
          as _i3.Future<_i4.BaseResponse<List<_i8.OccasionModel>>>);

  @override
  _i3.Future<_i4.BaseResponse<_i9.ProductDetailsEntity>> getProductDetails({
    required String? productId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getProductDetails, [], {#productId: productId}),
            returnValue:
                _i3.Future<_i4.BaseResponse<_i9.ProductDetailsEntity>>.value(
                  _i6.dummyValue<_i4.BaseResponse<_i9.ProductDetailsEntity>>(
                    this,
                    Invocation.method(#getProductDetails, [], {
                      #productId: productId,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.BaseResponse<_i9.ProductDetailsEntity>>);

  @override
  _i3.Future<_i4.BaseResponse<List<_i10.CategoryEntity>>> getAllCategories() =>
      (super.noSuchMethod(
            Invocation.method(#getAllCategories, []),
            returnValue:
                _i3.Future<_i4.BaseResponse<List<_i10.CategoryEntity>>>.value(
                  _i6.dummyValue<_i4.BaseResponse<List<_i10.CategoryEntity>>>(
                    this,
                    Invocation.method(#getAllCategories, []),
                  ),
                ),
          )
          as _i3.Future<_i4.BaseResponse<List<_i10.CategoryEntity>>>);
}
