name: Shorebird Patch

on:
  push:
    branches:
      - ci/cd

env:
  SHOREBIRD_TOKEN: ${{ secrets.SHOREBIRD_TOKEN }}

jobs:
  patch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Shorebird
        uses: shorebirdtech/setup-shorebird@v1
        with:
          cache: true

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Create .env
        env:
          ENV_FILE: ${{ secrets.ENV_FILE }}
        run: |
          printf '%s\n' "$ENV_FILE" > .env

      - name: Install dependencies
        run: flutter pub get

      - name: Generate code
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Shorebird Patch
        uses: shorebirdtech/shorebird-patch@v1
        with:
          platform: android
          release-version: latest